-- Migration generated by dbdev add at: 2026-10-03 14:09:14
-- Extension: pgledger
-- Default version: 0.0.1
-- Comment: Double-entry ledger for Postgres, inspired by TigerBeetle
-------------------------------------- Initial installation of version: 0.0.1
select pgtle.install_extension('pgledger', '0.0.1', $comment_yFRmeRFDKbTBeF7x$Double-entry ledger for Postgres, inspired by TigerBeetle$comment_yFRmeRFDKbTBeF7x$, $sql_yFRmeRFDKbTBeF7x$-- Makes a table append-only. Statement-level so it also covers TRUNCATE.
CREATE OR REPLACE FUNCTION @extschema@.raise_immutable()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION '%.% is append-only: % is not allowed',
        TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP;
END;
$$ LANGUAGE plpgsql;


-- Only the table's create function, named by the trigger argument, may write. It runs as
-- SECURITY DEFINER, so its inserts run as the table owner; anyone else granted INSERT is
-- rejected here. The owner itself is trusted.
CREATE OR REPLACE FUNCTION @extschema@.raise_direct_insert()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_class c
                   WHERE c.oid = TG_RELID
                     AND pg_catalog.pg_get_userbyid(c.relowner) = current_user) THEN
        RAISE EXCEPTION '%.% is written by %.%(); INSERTing into it directly is not allowed',
            TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_TABLE_SCHEMA, TG_ARGV[0];
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;


-- code, external_id and external_timestamp are opaque caller data. Both balance requirements
-- at once would pin the balance to zero. create_accounts() checks every rule and reports it as
-- a code, and stamps timestamp; the CHECKs are backstops. ledger is any positive integer the
-- caller chooses; there is no ledgers table, so a new value simply starts a new ledger.
CREATE TABLE @extschema@.accounts (
    id                 uuid        PRIMARY KEY,
    ledger             integer     NOT NULL CHECK (ledger > 0),
    code               integer     NOT NULL CHECK (code BETWEEN 1 AND 65535),
    external_id        uuid,
    external_timestamp timestamptz,

    require_credit_balance boolean NOT NULL DEFAULT false,
    require_debit_balance  boolean NOT NULL DEFAULT false,

    timestamp          timestamptz NOT NULL,

    CONSTRAINT accounts_one_balance_requirement
        CHECK (NOT (require_credit_balance AND require_debit_balance)),

    -- Unused since the composite FKs were dropped; kept in case they return.
    UNIQUE (id, ledger)
);

CREATE INDEX accounts_timestamp_idx ON @extschema@.accounts (timestamp);
CREATE INDEX accounts_ledger_idx ON @extschema@.accounts (ledger);
CREATE INDEX accounts_code_idx ON @extschema@.accounts (code);
CREATE INDEX accounts_external_id_idx ON @extschema@.accounts (external_id)
    WHERE external_id IS NOT NULL;
CREATE INDEX accounts_external_timestamp_idx ON @extschema@.accounts (external_timestamp)
    WHERE external_timestamp IS NOT NULL;

CREATE TRIGGER accounts_no_direct_insert
    BEFORE INSERT ON @extschema@.accounts
    FOR EACH STATEMENT EXECUTE FUNCTION @extschema@.raise_direct_insert('create_accounts');

CREATE TRIGGER accounts_immutable
    BEFORE UPDATE OR DELETE OR TRUNCATE ON @extschema@.accounts
    FOR EACH STATEMENT EXECUTE FUNCTION @extschema@.raise_immutable();

-- Value flows credit -> debit. create_transfers() validates the ledger and accounts itself; the
-- CHECKs are backstops. It also stamps timestamp. For a balancing transfer amount is what
-- actually moved, after the clamp; the flags record that it was one.
--
-- The row type is also create_transfers()'s input, where every rule is checked and reported
-- as a code. amount is plain numeric so that a cast into this type can't round a fraction or
-- overflow before those checks see it. Amounts and running totals are capped at TigerBeetle's
-- u128 (2^128 - 1) so that every row can be exported to it.
CREATE TABLE @extschema@.transfers (
    id                 uuid        PRIMARY KEY,
    ledger             integer     NOT NULL CHECK (ledger > 0),
    debit_account_id   uuid        NOT NULL,
    credit_account_id  uuid        NOT NULL,
    amount             numeric     NOT NULL
        CHECK (amount > 0 AND amount = trunc(amount)
               AND amount <= 340282366920938463463374607431768211455),
    code               integer     NOT NULL CHECK (code BETWEEN 1 AND 65535),
    external_id        uuid,
    external_timestamp timestamptz,

    balancing_debit    boolean     NOT NULL DEFAULT false,
    balancing_credit   boolean     NOT NULL DEFAULT false,

    timestamp          timestamptz NOT NULL,

    CHECK (debit_account_id <> credit_account_id)
);

CREATE INDEX transfers_debit_account_id_idx ON @extschema@.transfers (debit_account_id);
CREATE INDEX transfers_credit_account_id_idx ON @extschema@.transfers (credit_account_id);
CREATE INDEX transfers_ledger_timestamp_idx ON @extschema@.transfers (ledger, timestamp);
CREATE INDEX transfers_timestamp_idx ON @extschema@.transfers (timestamp);
CREATE INDEX transfers_code_idx ON @extschema@.transfers (code);
CREATE INDEX transfers_external_id_idx ON @extschema@.transfers (external_id)
    WHERE external_id IS NOT NULL;
CREATE INDEX transfers_external_timestamp_idx ON @extschema@.transfers (external_timestamp)
    WHERE external_timestamp IS NOT NULL;

CREATE TRIGGER transfers_no_direct_insert
    BEFORE INSERT ON @extschema@.transfers
    FOR EACH STATEMENT EXECUTE FUNCTION @extschema@.raise_direct_insert('create_transfers');

CREATE TRIGGER transfers_immutable
    BEFORE UPDATE OR DELETE OR TRUNCATE ON @extschema@.transfers
    FOR EACH STATEMENT EXECUTE FUNCTION @extschema@.raise_immutable();

-- Running totals per account, two rows per transfer. version is gapless; a writer on a stale
-- snapshot fails on the primary key instead of forking the chain.
CREATE TABLE @extschema@.account_balances (
    account_id     uuid          NOT NULL,
    version        bigint        NOT NULL CHECK (version > 0),
    transfer_id    uuid          NOT NULL,
    debits_posted  numeric(39,0) NOT NULL
        CHECK (debits_posted  BETWEEN 0 AND 340282366920938463463374607431768211455),
    credits_posted numeric(39,0) NOT NULL
        CHECK (credits_posted BETWEEN 0 AND 340282366920938463463374607431768211455),

    PRIMARY KEY (account_id, version),
    UNIQUE (transfer_id, account_id)
);

CREATE TRIGGER account_balances_no_direct_insert
    BEFORE INSERT ON @extschema@.account_balances
    FOR EACH STATEMENT EXECUTE FUNCTION @extschema@.raise_direct_insert('create_transfers');

CREATE TRIGGER account_balances_immutable
    BEFORE UPDATE OR DELETE OR TRUNCATE ON @extschema@.account_balances
    FOR EACH STATEMENT EXECUTE FUNCTION @extschema@.raise_immutable();

-- Accounts go through create_accounts() and posting through create_transfers(). Grants to
-- named roles (e.g. default privileges) aren't covered by this; the no_direct_insert triggers
-- reject those.
REVOKE INSERT ON @extschema@.accounts, @extschema@.transfers, @extschema@.account_balances
    FROM PUBLIC;


-- One row of create_accounts()'s result, in input order. code is 'ok' or the first failed
-- check:
--   values:        timestamp_must_not_be_set, id_not_set, ledger_invalid, code_invalid,
--                  flags_are_mutually_exclusive (both balance requirements set)
--   relationships: id_already_exists
CREATE TYPE @extschema@.account_result AS (
    ord        integer,
    account_id uuid,
    code       text
);

-- Creates a batch of accounts, each row getting its own result; a rejected row doesn't abort
-- the others. Inputs are accounts rows with timestamp left NULL. A NULL balance requirement
-- counts as false. A repeated id is created at most once: the first copy that passes the other
-- checks wins and later copies get id_already_exists. A concurrent insert of the same id fails
-- the whole call on the primary key.
CREATE OR REPLACE FUNCTION @extschema@.create_accounts(inputs @extschema@.accounts[])
RETURNS SETOF @extschema@.account_result AS $$
BEGIN
    IF inputs IS NULL OR cardinality(inputs) = 0 THEN
        RETURN;
    END IF;

    -- accounts[] accepts any number of dimensions; Postgres doesn't enforce them.
    IF array_ndims(inputs) <> 1 THEN
        RAISE EXCEPTION 'create_accounts expects a one-dimensional array, got % dimensions',
            array_ndims(inputs);
    END IF;

    RETURN QUERY
    WITH checks AS (
        -- The first failed check, the row's own values before its lookup.
        SELECT t.*,
               CASE
                   WHEN t.timestamp IS NOT NULL THEN 'timestamp_must_not_be_set'
                   WHEN t.id IS NULL THEN 'id_not_set'
                   WHEN t.ledger IS NULL OR t.ledger <= 0 THEN 'ledger_invalid'
                   WHEN t.code IS NULL OR t.code NOT BETWEEN 1 AND 65535 THEN 'code_invalid'
                   WHEN t.require_credit_balance AND t.require_debit_balance
                       THEN 'flags_are_mutually_exclusive'
                   WHEN a.id IS NOT NULL THEN 'id_already_exists'
               END AS fail
        -- ORDINALITY counts from 1 whatever the array's lower bound, so no rebase is needed.
        FROM unnest(inputs) WITH ORDINALITY
             AS t(id, ledger, code, external_id, external_timestamp,
                  require_credit_balance, require_debit_balance, timestamp, ord)
        -- One index probe per row; see create_transfers() for why LIMIT 1.
        LEFT JOIN LATERAL (SELECT a.id FROM @extschema@.accounts a
                           WHERE a.id = t.id LIMIT 1) a ON true
    ),
    -- Repeats within the batch, counted only among rows that passed, so a rejected first copy
    -- doesn't block a later one.
    results AS (
        SELECT c.*,
               CASE
                   WHEN c.fail IS NOT NULL THEN c.fail
                   WHEN row_number() OVER (PARTITION BY c.fail IS NULL, c.id ORDER BY c.ord) > 1
                       THEN 'id_already_exists'
               END AS outcome
        FROM checks c
    ),
    insert_accounts AS (
        INSERT INTO @extschema@.accounts
        SELECT r.id, r.ledger, r.code, r.external_id, r.external_timestamp,
               COALESCE(r.require_credit_balance, false),
               COALESCE(r.require_debit_balance,  false),
               clock_timestamp()
        FROM results r
        WHERE r.outcome IS NULL
        ORDER BY r.ord
    )
    SELECT r.ord::integer, r.id, COALESCE(r.outcome, 'ok')
    FROM results r
    ORDER BY r.ord;
END;
$$ LANGUAGE plpgsql
-- Runs as the owner, the only role that may insert into accounts.
SECURITY DEFINER
SET search_path = @extschema@, pg_temp
SET plan_cache_mode = force_generic_plan;


-- One row of create_transfers()'s result, in input order. code is 'ok' or the first failed
-- check:
--   values:        timestamp_must_not_be_set, id_not_set, ledger_invalid,
--                  amount_must_be_positive, code_invalid, accounts_must_be_different
--   relationships: id_already_exists, debit_account_not_found,
--                  credit_account_not_found, debit_account_ledger_mismatch,
--                  credit_account_ledger_mismatch
--   balances:      overflows_debits_posted, overflows_credits_posted (a running total would
--                  pass 2^128 - 1), exceeds_credits, exceeds_debits (also a balancing transfer
--                  that would move nothing: exceeds_credits if the debit side is balancing and
--                  already at zero)
CREATE TYPE @extschema@.transfer_result AS (
    ord         integer,
    transfer_id uuid,
    code        text
);

-- Posts a batch TigerBeetle-style: each row gets its own result and a rejected row doesn't
-- abort the others. Inputs are transfers rows with timestamp left NULL. The balancing flags
-- make amount a maximum, as in TigerBeetle: balancing_debit moves no more than keeps the debit
-- account's debits from exceeding its credits, balancing_credit no more than keeps the credit
-- account's credits from exceeding its debits, and both take the smaller. With either flag a
-- NULL amount means no cap. A NULL flag counts as false. Phase 2 is one linear walk over in-memory balances in batch order, so a
-- rejected row never affects later ones. A repeated id posts at most once; later copies get
-- id_already_exists. A concurrent insert of the same id fails the whole call on the primary key.
CREATE OR REPLACE FUNCTION @extschema@.create_transfers(inputs @extschema@.transfers[])
RETURNS SETOF @extschema@.transfer_result AS $$
DECLARE
    -- ord: a row's 1-based position in inputs, its identity throughout (ids can repeat).
    -- rank: 1..n per distinct account touched; account state lives in arrays indexed by rank.

    -- One per input, indexed by ord. Phase 1 fills in every code; candidates start as
    -- 'ok' and the walk overwrites the ones it rejects.
    results @extschema@.transfer_result[];

    -- Rows that passed phase 1, in batch order; other fields come from inputs[ord].
    candidate_count       integer;
    candidate_ord         integer[];
    candidate_id_group    integer[];   -- same number for rows sharing an id
    candidate_debit_rank  integer[];
    candidate_credit_rank integer[];

    -- Per rank: the account, and its latest balance row as the walk advances it.
    ranked_accounts @extschema@.accounts[];
    ranked_balances @extschema@.account_balances[];

    id_group_posted boolean[];

    -- Walk output, preallocated and filled up to accepted_count, two balance rows per transfer
    -- (growing element by element costs about twice as much).
    accepted_count integer := 0;
    new_transfers  @extschema@.transfers[];
    new_balances   @extschema@.account_balances[];

    candidate_index integer;
    ord             integer;
    candidate       @extschema@.transfers;
    debit_rank      integer;
    credit_rank     integer;
    amount          numeric;
    debit_balance   @extschema@.account_balances;
    credit_balance  @extschema@.account_balances;
    new_transfer    @extschema@.transfers;

    -- TigerBeetle's u128 limit, for amounts and running totals.
    u128_max CONSTANT numeric := 340282366920938463463374607431768211455;
BEGIN
    IF inputs IS NULL OR cardinality(inputs) = 0 THEN
        RETURN;
    END IF;

    -- transfers[] accepts any number of dimensions; Postgres doesn't enforce them.
    IF array_ndims(inputs) <> 1 THEN
        RAISE EXCEPTION 'create_transfers expects a one-dimensional array, got % dimensions',
            array_ndims(inputs);
    END IF;

    -- The walk reads inputs[ord]; rebase arrays like '[0:1]={...}' so indexes start at 1.
    IF array_lower(inputs, 1) <> 1 THEN
        inputs := ARRAY(SELECT unnest(inputs));
    END IF;

    -- Phase 1 plus phase 2's lock-free setup, before any lock is taken.
    WITH checks AS (
        -- Phase 1: the first failed check, the row's own values before its lookups.
        -- u128_max is the range limit and also catches NaN and Infinity, which sort above
        -- it; NULL account ids fall through to the not-found checks.
        SELECT t.ord, t.id, t.debit_account_id, t.credit_account_id,
               CASE
                   WHEN t.timestamp IS NOT NULL THEN 'timestamp_must_not_be_set'
                   WHEN t.id IS NULL THEN 'id_not_set'
                   WHEN t.ledger IS NULL OR t.ledger <= 0 THEN 'ledger_invalid'
                   -- NULL is no cap, allowed only on a balancing transfer.
                   WHEN CASE WHEN t.amount IS NULL
                             THEN NOT (t.balancing_debit IS TRUE OR t.balancing_credit IS TRUE)
                             ELSE t.amount <= 0 OR t.amount <> trunc(t.amount) OR t.amount > u128_max
                        END
                       THEN 'amount_must_be_positive'
                   WHEN t.code IS NULL OR t.code NOT BETWEEN 1 AND 65535 THEN 'code_invalid'
                   WHEN t.debit_account_id = t.credit_account_id
                       THEN 'accounts_must_be_different'
                   WHEN tx.id  IS NOT NULL THEN 'id_already_exists'
                   WHEN da.id IS NULL THEN 'debit_account_not_found'
                   WHEN ca.id IS NULL THEN 'credit_account_not_found'
                   WHEN da.ledger <> t.ledger THEN 'debit_account_ledger_mismatch'
                   WHEN ca.ledger <> t.ledger THEN 'credit_account_ledger_mismatch'
               END AS fail
        FROM unnest(inputs) WITH ORDINALITY
             AS t(id, ledger, debit_account_id, credit_account_id,
                  amount, code, external_id, external_timestamp,
                  balancing_debit, balancing_credit, timestamp, ord)
        -- One index probe per row. As plain joins or an EXISTS, the 10-row unnest estimate
        -- gets hash joins over seq scans of accounts and a hashed subplan over
        -- all of transfers; LIMIT 1 keeps each lookup a parameterized subquery.
        LEFT JOIN LATERAL (SELECT tx.id FROM @extschema@.transfers tx
                           WHERE tx.id = t.id LIMIT 1) tx ON true
        LEFT JOIN LATERAL (SELECT a.id, a.ledger FROM @extschema@.accounts a
                           WHERE a.id = t.debit_account_id LIMIT 1) da ON true
        LEFT JOIN LATERAL (SELECT a.id, a.ledger FROM @extschema@.accounts a
                           WHERE a.id = t.credit_account_id LIMIT 1) ca ON true
    ),
    candidates AS (
        SELECT c.ord, c.id, c.debit_account_id, c.credit_account_id,
               row_number() OVER (ORDER BY c.ord) AS candidate_index,
               dense_rank()  OVER (ORDER BY c.id) AS id_group
        FROM checks c
        WHERE c.fail IS NULL
    ),
    -- Ranks come from one dense_rank over the legs. Don't join candidates back to ranks:
    -- generic plans assume unnest yields 10 rows, which makes that join quadratic.
    legs AS (
        SELECT l.candidate_index, l.is_debit_leg, l.account_id,
               dense_rank() OVER (ORDER BY l.account_id) AS rank
        FROM (SELECT cn.candidate_index, true AS is_debit_leg,
                     cn.debit_account_id AS account_id
              FROM candidates cn
              UNION ALL
              SELECT cn.candidate_index, false, cn.credit_account_id
              FROM candidates cn) l
    ),
    -- Safe to read before the lock: accounts is immutable.
    ranks AS (
        SELECT DISTINCT lg.rank, lg.account_id FROM legs lg
    )
    SELECT result_array.results,
           candidate_arrays.ords, candidate_arrays.id_groups,
           leg_arrays.debit_ranks, leg_arrays.credit_ranks,
           account_array.accounts
      INTO results,
           candidate_ord, candidate_id_group,
           candidate_debit_rank, candidate_credit_rank,
           ranked_accounts
    FROM (SELECT array_agg(ROW(c.ord, c.id, COALESCE(c.fail, 'ok'))::@extschema@.transfer_result
                           ORDER BY c.ord) AS results
          FROM checks c) result_array,
         (SELECT COALESCE(array_agg(cn.ord::int      ORDER BY cn.candidate_index), '{}') AS ords,
                 COALESCE(array_agg(cn.id_group::int ORDER BY cn.candidate_index), '{}') AS id_groups
          FROM candidates cn) candidate_arrays,
         (SELECT COALESCE(array_agg(lg.rank::int ORDER BY lg.candidate_index)
                              FILTER (WHERE lg.is_debit_leg), '{}') AS debit_ranks,
                 COALESCE(array_agg(lg.rank::int ORDER BY lg.candidate_index)
                              FILTER (WHERE NOT lg.is_debit_leg), '{}') AS credit_ranks
          FROM legs lg) leg_arrays,
         (SELECT COALESCE(array_agg(a ORDER BY rk.rank), '{}') AS accounts
          FROM ranks rk
          JOIN @extschema@.accounts a ON a.id = rk.account_id) account_array;

    -- Phase 2: balance rules.
    candidate_count := cardinality(candidate_ord);

    IF candidate_count > 0 THEN
        -- Lock in id order to avoid deadlocks. The locks are held until commit, so keep
        -- the work after this to load, walk and insert.
        PERFORM a.id FROM @extschema@.accounts a
        -- ANY over an array keeps this an index scan; IN (SELECT ... unnest) gets a hash
        -- join over a seq scan of accounts in the generic plan.
        WHERE a.id = ANY(ARRAY(SELECT s.id FROM unnest(ranked_accounts) s))
        ORDER BY a.id
        FOR NO KEY UPDATE;

        -- Separate statement so its snapshot postdates the lock. An account never posted to
        -- starts at version 0 with zero totals.
        SELECT array_agg(ROW(s.id, COALESCE(b.version, 0), NULL,
                             COALESCE(b.debits_posted, 0), COALESCE(b.credits_posted, 0)
                            )::@extschema@.account_balances
                         ORDER BY s.ordinality)
          INTO ranked_balances
        FROM unnest(ranked_accounts) WITH ORDINALITY AS s
        LEFT JOIN LATERAL (
            SELECT ab.version, ab.debits_posted, ab.credits_posted
            FROM @extschema@.account_balances ab
            WHERE ab.account_id = s.id
            ORDER BY ab.version DESC
            LIMIT 1
        ) b ON true;
    END IF;

    id_group_posted := array_fill(false, ARRAY[candidate_count]);
    new_transfers   := array_fill(NULL::@extschema@.transfers,        ARRAY[candidate_count]);
    new_balances    := array_fill(NULL::@extschema@.account_balances, ARRAY[2 * candidate_count]);

    FOR candidate_index IN 1 .. candidate_count LOOP
        ord := candidate_ord[candidate_index];

        -- An earlier row with this id already posted in this batch.
        IF id_group_posted[candidate_id_group[candidate_index]] THEN
            results[ord].code := 'id_already_exists';
            CONTINUE;
        END IF;

        candidate   := inputs[ord];
        debit_rank  := candidate_debit_rank[candidate_index];
        credit_rank := candidate_credit_rank[candidate_index];
        -- Balancing clamps toward zero balance. LEAST ignores NULL, so an uncapped amount
        -- takes the whole available balance.
        -- trunc() drops any trailing zeros (2.0 -> 2); phase 1 ensured a whole number.
        amount      := trunc(candidate.amount);
        IF candidate.balancing_debit THEN
            amount := LEAST(amount, GREATEST(0, ranked_balances[debit_rank].credits_posted
                                                - ranked_balances[debit_rank].debits_posted));
        END IF;
        IF candidate.balancing_credit THEN
            amount := LEAST(amount, GREATEST(0, ranked_balances[credit_rank].debits_posted
                                                - ranked_balances[credit_rank].credits_posted));
        END IF;
        -- Nothing to move: rejected, as in TigerBeetle, with the debit side reported first.
        IF amount = 0 THEN
            results[ord].code := CASE
                WHEN candidate.balancing_debit
                     AND ranked_balances[debit_rank].credits_posted
                         <= ranked_balances[debit_rank].debits_posted
                    THEN 'exceeds_credits'
                ELSE 'exceeds_debits'
            END;
            CONTINUE;
        END IF;

        -- Advance copies; a rejected row just drops them. Phase 1 guarantees the two ranks
        -- differ.
        debit_balance  := ranked_balances[debit_rank];
        credit_balance := ranked_balances[credit_rank];
        debit_balance.debits_posted   := debit_balance.debits_posted   + amount;
        credit_balance.credits_posted := credit_balance.credits_posted + amount;

        -- Overflow before the balance rules, debit account first, as in TigerBeetle.
        IF debit_balance.debits_posted > u128_max THEN
            results[ord].code := 'overflows_debits_posted';
            CONTINUE;
        ELSIF credit_balance.credits_posted > u128_max THEN
            results[ord].code := 'overflows_credits_posted';
            CONTINUE;
        END IF;

        -- Each side can break only one rule; the debit account is checked first, as in
        -- TigerBeetle.
        IF ranked_accounts[debit_rank].require_credit_balance
           AND debit_balance.debits_posted > debit_balance.credits_posted THEN
            results[ord].code := 'exceeds_credits';
            CONTINUE;
        ELSIF ranked_accounts[credit_rank].require_debit_balance
              AND credit_balance.credits_posted > credit_balance.debits_posted THEN
            results[ord].code := 'exceeds_debits';
            CONTINUE;
        END IF;

        debit_balance.version      := debit_balance.version  + 1;
        debit_balance.transfer_id  := candidate.id;
        credit_balance.version     := credit_balance.version + 1;
        credit_balance.transfer_id := candidate.id;
        ranked_balances[debit_rank]  := debit_balance;
        ranked_balances[credit_rank] := credit_balance;
        id_group_posted[candidate_id_group[candidate_index]] := true;

        new_transfer                  := candidate;
        new_transfer.amount           := amount;   -- the walk's amount, not the input's
        new_transfer.balancing_debit  := COALESCE(candidate.balancing_debit,  false);
        new_transfer.balancing_credit := COALESCE(candidate.balancing_credit, false);
        new_transfer.timestamp        := clock_timestamp();

        accepted_count := accepted_count + 1;
        new_transfers[accepted_count]        := new_transfer;
        new_balances[2 * accepted_count - 1] := debit_balance;
        new_balances[2 * accepted_count]     := credit_balance;
    END LOOP;

    RETURN QUERY
    WITH insert_transfers AS (
        INSERT INTO @extschema@.transfers
        SELECT * FROM unnest(new_transfers[1:accepted_count])
    ),
    insert_balances AS (
        INSERT INTO @extschema@.account_balances
        SELECT * FROM unnest(new_balances[1:2 * accepted_count])
    )
    SELECT * FROM unnest(results);
END;
$$ LANGUAGE plpgsql
-- Runs as the owner, the only role that may insert into transfers and account_balances.
SECURITY DEFINER
SET search_path = @extschema@, pg_temp
-- Planning costs more than running, and custom plans for small arrays keep winning. Plan
-- once: every access path is an index lookup.
SET plan_cache_mode = force_generic_plan;


-- Every account's latest totals, zeros if never posted to. Upgrades can only append columns.
CREATE VIEW @extschema@.current_balances AS
SELECT
    a.id        AS account_id,
    a.ledger,
    COALESCE(b.version,        0) AS version,
    COALESCE(b.debits_posted,  0) AS debits_posted,
    COALESCE(b.credits_posted, 0) AS credits_posted,
    COALESCE(b.debits_posted,  0) - COALESCE(b.credits_posted, 0) AS balance
FROM @extschema@.accounts a
LEFT JOIN LATERAL (
    SELECT ab.version, ab.debits_posted, ab.credits_posted
    FROM @extschema@.account_balances ab
    WHERE ab.account_id = a.id
    ORDER BY ab.version DESC
    LIMIT 1
) b ON true;
$sql_yFRmeRFDKbTBeF7x$, array[]::text[] );


-- Setting default version to:0.0.1
select pgtle.set_default_version('pgledger', '0.0.1');
